### ISSUE TITLE
How to modify dataset?

### ISSUE THREAD

**Issue by y2t** [ShamylZakariya/StickyHeaders#10]
First of all thanks for this lib, it's great!

I call the `notifySectionItemChanged(sectionIndex, itemIndex)` method.

But had a problem is
`java.lang.IllegalArgumentException: view is not a child, cannot hide android.widget.LinearLayout{21e33088 V.E...CL ......I. 0,612-600,683}`
`java.lang.IllegalArgumentException: Tmp detached view should be removed from RecyclerView before it can be recycled`

Thanks in advance

**Comment by ShamylZakariya** [comment]
The only reason I can think that that would be called is if `sectionIndex` or `itemIndex` are wrong in some way.

The `itemIndex` is relative to the section. So section N's first item would have `itemIndex` of 0
