### ISSUE TITLE
Publish version 0.7.9 to Maven

### ISSUE THREAD

**Issue by ibrcic** [ShamylZakariya/StickyHeaders#106]
As far as I can see, the new version from yesterday is still not on maven, could you publish it?

https://mvnrepository.com/artifact/org.zakariya.stickyheaders/stickyheaders

**Comment by ShamylZakariya** [comment]
@ibrcic Thanks for the heads up - I'm looking into this right now. First, can you confirm that this is not working? I've been out of the loop of android development for a while, previously it was enough to simply publish my build to jcenter.

Here, it _looks_ like the package should be available on maven:
https://bintray.com/shamylzakariya/maven/stickyheaders/0.7.9

**Comment by ShamylZakariya** [comment]
So it looks like my bintray upload grade scripts aren't including source; which is preventing the "Add to JCenter" functionality from working. I'm going to look into how to update my build scripts.

**Comment by ShamylZakariya** [comment]
Can you test 0.7.10? I believe I've fixed my maven issues, and was able to bring it in to a test project via `implementation 'org.zakariya.stickyheaders:stickyheaders:0.7.10'` - but I'd like to know if it works not-on-my-computer.

**Comment by ibrcic** [comment]
Hi, yes I can confirm that version 0.7.10 is indeed working.
