### ISSUE TITLE
Load More with sticky headers

### ISSUE THREAD

**Issue by mohit-trantor** [ShamylZakariya/StickyHeaders#13]
Can you please explain, How to use Load More functionality in this with sticky headers? 

I am using the following link for load more feature:
https://guides.codepath.com/android/Endless-Scrolling-with-AdapterViews-and-RecyclerView
This works fine if I use LinearLayoutManager but that removes the Sticky header feature.

I want both the feature in one. Can you help me on this?

**Comment by ShamylZakariya** [comment]
If you look at the source for the `EndlessRecyclerViewScrollListener` you'll see it's specifically designed for use with `LinearLayoutManager`, `GridLayoutManager` and `StaggeredGridLayoutManager`. Remember, *never just cut & paste code*. Read it too.

This seems like a useful addition for StickyHeaders though, so I will put this in my feature queue.

**Comment by mohit-trantor** [comment]
I have finally done this by mixing extending LinearLayoutManager and adding code of StickyHeaderLayoutManager. It is working great.

Here is the file: https://gist.github.com/mohit-trantor/aca421a2359541ad23a0b4b827fc20d7

**Comment by ShamylZakariya** [comment]
My plan is to add this functionality to my demo app, including the use of a loading progress view. I'll post a followup when it's implemented.

**Comment by mohit-trantor** [comment]
ok Thanks

**Comment by ShamylZakariya** [comment]
I've implemented a pretty solid paged loading mechanism for endless scrolling, including support for an "exhausted" paged data source, such that there's a concrete way to handle when no more items are available from the data source.

https://github.com/ShamylZakariya/StickyHeaders/releases/tag/v0.7.0

**Comment by mohit-trantor** [comment]
Great!!! Thanks..I will check that and let you know
