### ISSUE TITLE
Collapsed Header overlaps with last item of previous section

### ISSUE THREAD

**Issue by cordeveloper** [ShamylZakariya/StickyHeaders#14]
With headers A, B, and C:

Collapse header B. Scroll up so that C is the sticky header. Scroll back down to section A; the last item in the section now overlaps with header B.

Looks to be an issue with the layoutmanager class; I'll do some digging.

**Comment by cordeveloper** [comment]
Effectively, it seems the last item of the previous section is being triggered to draw one index too early, and then the header is drawn on top; not too familiar with layout managers so it may take me a bit to track down exactly where this is happening.

**Comment by cordeveloper** [comment]
Fixed it; when we skipped the header here:

```
                    if (isHeader) {
                        firstViewAdapterPosition--;
                        if (firstViewAdapterPosition < 0) {
                            break;
                        }
                    }
```

You can't assume that the new position isn't also a header; it may be collapsed or an empty section. Simply repeat the check for the header on the new position, and if it's still a header break out.

Great library!

**Comment by ShamylZakariya** [comment]
Good catch! I'll look into a fix pronto.

**Comment by ShamylZakariya** [comment]
I didn't see your PR for this. Thanks!
