### ISSUE TITLE
Get current visible item on screen

### ISSUE THREAD

**Issue by albertorusso90** [ShamylZakariya/StickyHeaders#19]
Hi, is there a way to find out which item (that is not a section header) is currently being displayed on the screen?

Thanks in advance

**Comment by ShamylZakariya** [comment]
No but it would not be hard to implement. Would your preferred use of this method return the adapter position of the first (non-header) item? Or the associated ViewHolder?

**Comment by albertorusso90** [comment]
oh thats great that you would implement this. For me it would be best if it returned the ViewHolder of the first (non-header) item

**Comment by ShamylZakariya** [comment]
OK, so I'm going sailing this weekend, will not be coding. But since this seems like a useful feature which won't break anything to add or otherwise change behavior, I'll see about doing this early next week.

**Comment by albertorusso90** [comment]
ok great, i already implemented a custom way to get the view of the most visible item from the sectioned list view but looking forward to see your implementation (mine is a bit buggy)

**Comment by ShamylZakariya** [comment]
This is implemented:
https://github.com/ShamylZakariya/StickyHeaders/releases/tag/v0.7.2
