### ISSUE TITLE
Doesn't support view type for ItemView?

### ISSUE THREAD

**Issue by Piasy** [ShamylZakariya/StickyHeaders#2]
It seems only support 4 types, TYPE_ITEM, TYPE_HEADER, TYPE_GHOST_HEADER or TYPE_FOOTER, so what could I do if my TYPE_ITEM has different sub types?

**Comment by ShamylZakariya** [comment]
That's not a use case I thought through, to be honest. I'm open to adding it if there's a graceful way to do it, but I know there's a lot of animated discussion out there about best practices for heterogenous view types in recyclerview.

**Comment by zdxiang** [comment]
so,it can not support some other types?

**Comment by ShamylZakariya** [comment]
I've implemented multiple item types in a fairly robust way. Hopefully it's useful to you.

https://github.com/ShamylZakariya/StickyHeaders/releases/tag/v0.7.0
