### ISSUE TITLE
findFirstVisibleItemPosition

### ISSUE THREAD

**Issue by ihsanbal** [ShamylZakariya/StickyHeaders#21]
For endless scrolling ,StickyHeaderLayoutManager need findFirstVisibleItemPosition() method.

**Comment by ShamylZakariya** [comment]
I've already implemented endless scrolling, and have methods *similar* to your request, such as `StickyHeaderLayoutManager:: getFirstVisibleItemViewHolder`, etc.

See https://github.com/ShamylZakariya/StickyHeaders/blob/master/stickyheaders/src/main/java/org/zakariya/stickyheaders/PagedLoadScrollListener.java

And the demo code here:
https://github.com/ShamylZakariya/StickyHeaders/blob/master/app/src/main/java/org/zakariya/stickyheadersapp/ui/PagedScrollDemoActivity.java#L38
