### ISSUE TITLE
Question. Is it possible to disable stickyheaders?

### ISSUE THREAD

**Issue by rusmichal** [ShamylZakariya/StickyHeaders#22]

**Comment by ShamylZakariya** [comment]
That's not something I'd considered. I assume you mean that you'd want the headers "stickiness" to be toggleable? Some headers sticky, some not, or based on some change in data, a header that was sticky ceases to be sticky?

**Comment by rusmichal** [comment]
I wanted just use you sectioning adapter without stikcyheaders. It works. I use just `LinearLayoutManager`

**Comment by ShamylZakariya** [comment]
The sectioning adapter works great with LinearLayoutManager. No need to do anything fancy. One of my app demos shows this.

**Comment by zero2424** [comment]
> Some headers sticky, some not, or based on some change in data, a header that was sticky ceases to be sticky

Is it possible to do like this? Some headers sticky, some not, based on some data, the "stickiness" capability doesn't need to be changed after initialized.
