### ISSUE TITLE
Delete all selection Failed.

### ISSUE THREAD

**Issue by waincent** [ShamylZakariya/StickyHeaders#27]
when I use toggleSectionSelected(index) method select all the selection. 

use  traverseSelection() to delete the select, use notifySectionRemoved(index) refresh data, but this no work. only delete one **section** once.

I find you code in SectioningAdapter-->notifySectionRemoved() --> notifyAllSectionsDataSetChanged() --> selectionStateBySection.clear();

I guess the problem here.

**Comment by ShamylZakariya** [comment]
I've tested this behavior thoroughly; in my tests it works correctly. My guess is you're not correctly modifying your underlying model correctly?
