### ISSUE TITLE
ScrollToPosition Issue

### ISSUE THREAD

**Issue by jhpassion0621** [ShamylZakariya/StickyHeaders#28]
I added StickyheaderLayoutManager. It works well. But when I use scrollToPosition(int position) of this layout manager, it doesn't work well. How should I use scrollToPosition function?
What is position on recycler view of stickyheaders.

**Comment by akshaycrt2k** [comment]
I have the same issue. Everything works well except "recyclerView.scrollToPosition(position);"

**Comment by ShamylZakariya** [comment]
Can you describe what the scrolling behavior is doing incorrectly? 

If you run my demo app, in (e.g.) the AddressBook demo, there's a menu item looking like an arrow pointing down. Tap that and a dialog will open with scroll to position choices. They work for me (barring weirdness with collapsing appbarlayout).

See here:
https://github.com/ShamylZakariya/StickyHeaders/blob/master/app/src/main/java/org/zakariya/stickyheadersapp/ui/DemoActivity.java#L174

If you can describe how this is not working correctly let me know.

**Comment by akshaycrt2k** [comment]
Hi,
Sorry I forgot to edit my comment.
Turned out I was passing wrong position to that method.

Everything is working great.

**Comment by ShamylZakariya** [comment]
OK, good.
