### ISSUE TITLE
notifySectionFooterRemoved wrong index logic

### ISSUE THREAD

**Issue by TheLester** [ShamylZakariya/StickyHeaders#39]
At the end of the method  _notifySectionFooterRemoved_  you have such piece of code:

`notifyItemRemoved(section.adapterPosition + section.length - 1);`

Suppose i have 24 items in my section, one header and one footer (total item count -27),. I want to remove my footer So after my call  _notifySectionFooterRemoved_   _buildSectionIndex()_ will assign to section.length = 26 (24 (items)+ 2(header and ghost header)).

So _notifyItemRemoved(25)_ called - and thats wrong, should be _notifyItemRemoved(26)_

**Comment by TheLester** [comment]
https://github.com/ShamylZakariya/StickyHeaders/pull/40

**Comment by ShamylZakariya** [comment]
Thanks for catching this.
