### ISSUE TITLE
StickyHeaderLayoutManager not rendering

### ISSUE THREAD

**Issue by pfaffenrodt** [ShamylZakariya/StickyHeaders#5]
Attaching StickyHeaderLayoutManager. View ist empty.

LinearLayoutManager the Views are rendered.

supportLibraryVersion = '23.4.0'

**Comment by pfaffenrodt** [comment]
int parentBottom = getHeight() - getPaddingBottom();

parentBottom is "0"

**Comment by ShamylZakariya** [comment]
I need more information if I'm going to be able to fix this. Perhaps you can post some of your code.

**Comment by pfaffenrodt** [comment]
I dont have code anymore. Created own Adapter without sticky. 

If I correctly remeber, it can be reproduced with databinding. Or with the latest Support library. 

I look to that I provide some reproducing code.

**Comment by ShamylZakariya** [comment]
If you can provide repro code I'll see what I can do to fix this, but since I've not actually seen this in any of my use I can't, on my own, fix this bug.

**Comment by pfaffenrodt** [comment]
I just try to reproduce this bug. But I could not. This is so annoying.

**Comment by JulienRaad** [comment]
I am facing the same issue, the layout is empty when using StickyLayoutManager, but the items are rendered when i use a normal LinearLayoutManager but the headers are not sticky.  

What could be the issue ? 

thank you

**Comment by ShamylZakariya** [comment]
@JulienRaad Can you post your code? I'd like to reproduce this bug to fix it.

**Comment by pfaffenrodt** [comment]
Maybe the RecyclerView is in wrap_content mode.

```xml
<RelativeLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/activity_main"
    android:layout_width="match_parent"
    android:layout_height="match_parent">
    <android.support.v7.widget.RecyclerView
        android:id="@+id/recyclerView"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"/>
</RelativeLayout>
```

I just tried it. LinearLayoutManager supports wrap_content and StickyLayoutManger dont.
Well for me it is not necessary to support wrap_content, because in most cases RecyclerView has an fix size with "match_parent".

**Comment by JulienRaad** [comment]
Thats it ! Thumbs up mate @pfaffenrodt  @ShamylZakariya

**Comment by ShamylZakariya** [comment]
It honestly never occurred to me to wrap_content a recyclerview. Sounds like this is taken care of. Closing.

**Comment by EzequielMessore** [comment]
@pfaffenrodt working ?

**Comment by pfaffenrodt** [comment]
@EzequielMessore I dont understand your question. Solution is simple. Make sure height of your recyclerView is match_parent.

```xml

    <android.support.v7.widget.RecyclerView
        android:id="@+id/recyclerView"
        android:layout_width="match_parent"
        android:layout_height="match_parent"/>
```

**Comment by EzequielMessore** [comment]
@pfaffenrodt I changed it displayed, but it breaks the card.

**Comment by vishnuc156** [comment]
I got the same issue while using RecycleView inside the NestedScrollView.
When i change the StickyHeaderLayoutManager to LinearLayoutManager the list shows with header. But i need the header as Sticky. Below is my layout

<android.support.v4.widget.NestedScrollView
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    app:layout_behavior="@string/appbar_scrolling_view_behavior"
    tools:showIn="@layout/fragment_home"
    >
            <android.support.v7.widget.RecyclerView
                android:id="@+id/rvHomeCabinetList"
                android:layout_width="match_parent"
                android:layout_height="match_parent"/>
</android.support.v4.widget.NestedScrollView>
