### ISSUE TITLE
How to click on the head of a child view?

### ISSUE THREAD

**Issue by weinierfei** [ShamylZakariya/StickyHeaders#8]
How to click on the head of a child view?

**Comment by ShamylZakariya** [comment]
What are you asking? Do you want to click on a section header?

**Comment by ShamylZakariya** [comment]
I don't know what functionality you're asking for, but I just implemented collapsing sections, where you can call `SectioningAdapter::setSectionIsCollapsed` to collapse/expand sections. 

https://github.com/ShamylZakariya/StickyHeaders/commit/a07ffcbd11e959ca403cac0290bbdcad60030ada

I'm assuming this is what you are asking for, so I'm closing this.
