### ISSUE TITLE
Scrolling gets progressively slower the more sections there are

### ISSUE THREAD

**Issue by amitailanciano** [ShamylZakariya/StickyHeaders#9]
First of all thanks for this lib, it's great!

I'm running into some performance issues when there are a large number of sections, my use case is a list of events, each section is labeled with a date, and the items are events for that date.

It starts off smooth as butter, but the farther down the list you go the slower it gets. I profiled it and it looks like `updateHeaderPositions` takes more and more cycles the deeper down the list you go, to the point of being unusable at around the 500th section for my use case. I understand that number may vary depending on the implementation of the view holder methods, but nothing I'm doing is a long running blocking operation, I'm simply loading some data into a handful of views.

Is this a known issue with the library? If not, I am happy to provide my profiler .trace file if that would help

**Comment by ShamylZakariya** [comment]
I've been on vacation for a week, so sorry for the delay.

About how many items are there, on average, per section? I'm going to try to reproduce this, and see if there's a better way I can implement the `updateHeaderPositions` method. There are some places in my code where I thought, "I can optimize this later" and clearly later has arrived.

**Comment by ShamylZakariya** [comment]
I've identified the likely performance culprit, and will hopefully be pushing an update fixing this in the next day or so.

**Comment by ShamylZakariya** [comment]
Good news, I've fixed the performance issue.

https://github.com/ShamylZakariya/StickyHeaders/commit/afa2f286242e55b4ae96bd44a10fa9d812035c85

I'll be posting an updated build to bintray this evening.
