### ISSUE TITLE
Refactor AndroidX

### ISSUE THREAD

**Issue by TuonBondol** [ShamylZakariya/StickyHeaders#96]
Awesome library you made there, I have one question, do you plan to refactor to AndroidX anytime soon?

**Comment by saipsa** [comment]
@TuonBondol do you plan to create a PR?

**Comment by AlBlanc** [comment]
I just made a fork with up-to-date dependencies and migration to AndroidX -> https://github.com/Sportner/StickyHeaders

I am going to fix a few stuff and then publish it to maven. I'll let you know once it is done.

**Comment by TuonBondol** [comment]
@AlBlanc Okay, Thank you :)

**Comment by ShamylZakariya** [comment]
Done, available in 0.7.10
